sf1n = read.csv('인타임_네이버.csv')
sf2n = read.csv('승리호(2020)_네이버.csv')
sf3n = read.csv('로보캅_네이버.csv')
sf4n = read.csv('터미네이터_미래전쟁의시작_네이버.csv')
sf5n = read.csv('아바타_네이버.csv')
sf6n = read.csv('매트릭스_네이버.csv')
sf7n = read.csv('아이_로봇_네이버.csv')
sf8n = read.csv('컨택트_네이버.csv')
sf9n = read.csv('ET_네이버.csv')
sf10n = read.csv('테넷_네이버.csv')
sf11n = read.csv('마션_네이버.csv')
sf12n = read.csv('인터스텔라_네이버.csv')
sf13n = read.csv('엣지 오브 투모로우_네이버.csv')
sf14n = read.csv('그래비티_네이버.csv')
sf15n = read.csv('아마겟돈_네이버.csv')
sf16n = read.csv('지구가 멈추는 날_네이버.csv')
sf17n = read.csv('공각기동대_네이버.csv')
sf18n = read.csv('아일랜드_네이버.csv')
sf19n = read.csv('마이너리티 리포트_네이버.csv')
sf20n = read.csv('맨인블랙_네이버.csv')
sf21n = read.csv('혹성탈출_종의전쟁_네이버.csv')
sf22n = read.csv('프로메테우스_네이버.csv')
sf23n = read.csv('트론_새로운시작_네이버.csv')
sf24n = read.csv('패신저스_네이버.csv')
sf25n = read.csv('퍼시픽림_네이버.csv')
sf26n = read.csv('인셉션_네이버.csv')
sf27n = read.csv('더 문_네이버.csv')
sf28n = read.csv('레디 플레이어 원_네이버.csv')
sf29n = read.csv('어벤져스_엔드게임_네이버.csv')
sf30n = read.csv('토탈 리콜_네이버.csv')




